"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { Footer } from "@/components/Footer";
import { DinamicNav } from "@/components/DinamicNav";

const inter = Inter({ subsets: ["latin"] });

///export const metadata = {
///  title: "Create Next App",
///  description: "Generated by create next app",
///};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className="scroll-smooth">
      <body
        className={`${inter.className} h-dvh flex flex-col justify-between`}
      >
        <DinamicNav />
        <NextUIProvider>{children}</NextUIProvider>
        <Footer />
      </body>
    </html>
  );
}
